<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="7" passed="5">
  <reporter-output>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[C:\Users\satheeshnair\Desktop\infocampus\SourceCode\AppianJJ\ExecutionReports\AutomationTestReport.html]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[ - PASSED.]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[ - PASSED.]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[ - PASSED.]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[ - FAILED.]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[ - PASSED.]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[ - FAILED.]]>
    </line>
    <line>
      <![CDATA[ - PASSED.]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="229324" started-at="2019-05-30T14:21:34Z" finished-at="2019-05-30T14:25:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="229324" started-at="2019-05-30T14:21:34Z" finished-at="2019-05-30T14:25:23Z">
      <class name="regression.TC_AddNewPosition">
        <test-method status="PASS" signature="CreateErrorRepFolder()[pri:0, instance:regression.TC_AddNewPosition@10bdf5e5]" name="CreateErrorRepFolder" is-config="true" duration-ms="40" started-at="2019-05-30T14:21:34Z" finished-at="2019-05-30T14:21:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateErrorRepFolder -->
        <test-method status="PASS" signature="createExtentInstance(java.lang.String)[pri:0, instance:regression.TC_AddNewPosition@10bdf5e5]" name="createExtentInstance" is-config="true" duration-ms="13029" started-at="2019-05-30T14:21:34Z" finished-at="2019-05-30T14:21:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
            <line>
              <![CDATA[C:\Users\satheeshnair\Desktop\infocampus\SourceCode\AppianJJ\ExecutionReports\AutomationTestReport.html]]>
            </line>
          </reporter-output>
        </test-method> <!-- createExtentInstance -->
        <test-method status="PASS" signature="testcase()[pri:0, instance:regression.TC_AddNewPosition@10bdf5e5]" name="testcase" duration-ms="14867" started-at="2019-05-30T14:21:47Z" finished-at="2019-05-30T14:22:02Z">
          <reporter-output>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewPosition@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="2" started-at="2019-05-30T14:22:02Z" finished-at="2019-05-30T14:22:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testcase status=SUCCESS method=TC_AddNewPosition.testcase()[pri:0, instance:regression.TC_AddNewPosition@10bdf5e5] output=Exception in ExtentManager function]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - PASSED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="PASS" signature="header()[pri:1, instance:regression.TC_AddNewPosition@10bdf5e5]" name="header" duration-ms="4866" started-at="2019-05-30T14:22:02Z" finished-at="2019-05-30T14:22:07Z">
          <reporter-output>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
          </reporter-output>
        </test-method> <!-- header -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewPosition@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="2" started-at="2019-05-30T14:22:07Z" finished-at="2019-05-30T14:22:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=header status=SUCCESS method=TC_AddNewPosition.header()[pri:1, instance:regression.TC_AddNewPosition@10bdf5e5] output=Exception in ExtentManager function]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - PASSED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="PASS" signature="clickondemand()[pri:2, instance:regression.TC_AddNewPosition@10bdf5e5]" name="clickondemand" duration-ms="4638" started-at="2019-05-30T14:22:07Z" finished-at="2019-05-30T14:22:11Z">
          <reporter-output>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
          </reporter-output>
        </test-method> <!-- clickondemand -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewPosition@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="0" started-at="2019-05-30T14:22:11Z" finished-at="2019-05-30T14:22:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=clickondemand status=SUCCESS method=TC_AddNewPosition.clickondemand()[pri:2, instance:regression.TC_AddNewPosition@10bdf5e5] output=Exception in ExtentManager function]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - PASSED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="FAIL" signature="addnewposition()[pri:3, instance:regression.TC_AddNewPosition@10bdf5e5]" name="addnewposition" duration-ms="62975" started-at="2019-05-30T14:22:11Z" finished-at="2019-05-30T14:23:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add New position button missing]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add New position button missing
at org.testng.Assert.fail(Assert.java:96)
at pages.AddNewPosition.clickaddpositionbtn(AddNewPosition.java:145)
at regression.TC_AddNewPosition.addnewposition(TC_AddNewPosition.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
          </reporter-output>
        </test-method> <!-- addnewposition -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewPosition@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="1" started-at="2019-05-30T14:23:14Z" finished-at="2019-05-30T14:23:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addnewposition status=FAILURE method=TC_AddNewPosition.addnewposition()[pri:3, instance:regression.TC_AddNewPosition@10bdf5e5] output=Exception in ExtentManager function]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - FAILED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="PASS" signature="addposition()[pri:4, instance:regression.TC_AddNewPosition@10bdf5e5]" name="addposition" duration-ms="82875" started-at="2019-05-30T14:23:14Z" finished-at="2019-05-30T14:24:37Z">
          <reporter-output>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
          </reporter-output>
        </test-method> <!-- addposition -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewPosition@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="0" started-at="2019-05-30T14:24:37Z" finished-at="2019-05-30T14:24:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addposition status=SUCCESS method=TC_AddNewPosition.addposition()[pri:4, instance:regression.TC_AddNewPosition@10bdf5e5] output=Exception in ExtentManager function]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - PASSED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="FAIL" signature="submitposition()[pri:5, instance:regression.TC_AddNewPosition@10bdf5e5]" name="submitposition" duration-ms="35470" started-at="2019-05-30T14:24:37Z" finished-at="2019-05-30T14:25:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Position not submiited]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Position not submiited
at org.testng.Assert.fail(Assert.java:96)
at pages.AddNewPosition.clicksubmitbutton(AddNewPosition.java:385)
at regression.TC_AddNewPosition.submitposition(TC_AddNewPosition.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
          </reporter-output>
        </test-method> <!-- submitposition -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewPosition@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="1" started-at="2019-05-30T14:25:12Z" finished-at="2019-05-30T14:25:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=submitposition status=FAILURE method=TC_AddNewPosition.submitposition()[pri:5, instance:regression.TC_AddNewPosition@10bdf5e5] output=Exception in ExtentManager function]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - FAILED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="PASS" signature="logout()[pri:6, instance:regression.TC_AddNewPosition@10bdf5e5]" name="logout" duration-ms="8471" started-at="2019-05-30T14:25:12Z" finished-at="2019-05-30T14:25:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewPosition@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="1" started-at="2019-05-30T14:25:21Z" finished-at="2019-05-30T14:25:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logout status=SUCCESS method=TC_AddNewPosition.logout()[pri:6, instance:regression.TC_AddNewPosition@10bdf5e5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - PASSED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="FAIL" signature="tearDownFunction()[pri:0, instance:regression.TC_AddNewPosition@10bdf5e5]" name="tearDownFunction" is-config="true" duration-ms="2084" started-at="2019-05-30T14:25:21Z" finished-at="2019-05-30T14:25:23Z">
          <exception class="org.openqa.selenium.UnhandledAlertException">
            <message>
              <![CDATA[unexpected alert open: {Alert text : Your changes will be lost if you leave this page.}
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds: null
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'IN-SATHEESHS', ip: '10.210.219.231', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 74.0.3729.6 (255758eccf3d24..., userDataDir: C:\Users\SATHEE~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:62929}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 74.0.3729.169, webStorageEnabled: true}
Session ID: 7e2361459f616727cdcd43b467594dd0]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.UnhandledAlertException: unexpected alert open: {Alert text : Your changes will be lost if you leave this page.}
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds: null
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'IN-SATHEESHS', ip: '10.210.219.231', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 74.0.3729.6 (255758eccf3d24..., userDataDir: C:\Users\SATHEE~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:62929}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 74.0.3729.169, webStorageEnabled: true}
Session ID: 7e2361459f616727cdcd43b467594dd0
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:172)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:442)
at reusableLibrary.DriverFactory.tearDownFunction(DriverFactory.java:170)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.UnhandledAlertException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownFunction -->
      </class> <!-- regression.TC_AddNewPosition -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
