<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="6" passed="3">
  <reporter-output>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[C:\Users\satheeshnair\Desktop\infocampus\SourceCode\AppianJJ\ExecutionReports\AutomationTestReport.html]]>
    </line>
    <line>
      <![CDATA[ - PASSED.]]>
    </line>
    <line>
      <![CDATA[ - PASSED.]]>
    </line>
    <line>
      <![CDATA[ - FAILED.]]>
    </line>
    <line>
      <![CDATA[ - FAILED.]]>
    </line>
    <line>
      <![CDATA[ - FAILED.]]>
    </line>
    <line>
      <![CDATA[ - PASSED.]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="169003" started-at="2019-02-19T11:32:59Z" finished-at="2019-02-19T11:35:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="169003" started-at="2019-02-19T11:32:59Z" finished-at="2019-02-19T11:35:48Z">
      <class name="regression.TC_AddNewResource">
        <test-method status="PASS" signature="CreateErrorRepFolder()[pri:0, instance:regression.TC_AddNewResource@10bdf5e5]" name="CreateErrorRepFolder" is-config="true" duration-ms="47" started-at="2019-02-19T11:32:59Z" finished-at="2019-02-19T11:32:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateErrorRepFolder -->
        <test-method status="PASS" signature="createExtentInstance(java.lang.String)[pri:0, instance:regression.TC_AddNewResource@10bdf5e5]" name="createExtentInstance" is-config="true" duration-ms="10473" started-at="2019-02-19T11:32:59Z" finished-at="2019-02-19T11:33:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
            <line>
              <![CDATA[C:\Users\satheeshnair\Desktop\infocampus\SourceCode\AppianJJ\ExecutionReports\AutomationTestReport.html]]>
            </line>
          </reporter-output>
        </test-method> <!-- createExtentInstance -->
        <test-method status="PASS" signature="loginasvendor()[pri:0, instance:regression.TC_AddNewResource@10bdf5e5]" name="loginasvendor" duration-ms="8999" started-at="2019-02-19T11:33:09Z" finished-at="2019-02-19T11:33:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginasvendor -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewResource@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="0" started-at="2019-02-19T11:33:18Z" finished-at="2019-02-19T11:33:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginasvendor status=SUCCESS method=TC_AddNewResource.loginasvendor()[pri:0, instance:regression.TC_AddNewResource@10bdf5e5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - PASSED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="PASS" signature="clickontask()[pri:1, instance:regression.TC_AddNewResource@10bdf5e5]" name="clickontask" duration-ms="10525" started-at="2019-02-19T11:33:18Z" finished-at="2019-02-19T11:33:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickontask -->
        <test-method status="FAIL" signature="clickonresource()[pri:2, instance:regression.TC_AddNewResource@10bdf5e5]" name="clickonresource" duration-ms="30434" started-at="2019-02-19T11:33:29Z" finished-at="2019-02-19T11:33:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[no such demand]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: no such demand
at org.testng.Assert.fail(Assert.java:96)
at regression.TC_AddNewResource.clickonresource(TC_AddNewResource.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickonresource -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewResource@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="0" started-at="2019-02-19T11:33:29Z" finished-at="2019-02-19T11:33:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=clickontask status=SUCCESS method=TC_AddNewResource.clickontask()[pri:1, instance:regression.TC_AddNewResource@10bdf5e5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - PASSED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="FAIL" signature="addnewresource()[pri:3, instance:regression.TC_AddNewResource@10bdf5e5]" name="addnewresource" duration-ms="63590" started-at="2019-02-19T11:33:59Z" finished-at="2019-02-19T11:35:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to Click on Add position button]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to Click on Add position button
at org.testng.Assert.fail(Assert.java:96)
at regression.TC_AddNewResource.addnewresource(TC_AddNewResource.java:128)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addnewresource -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewResource@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="0" started-at="2019-02-19T11:33:59Z" finished-at="2019-02-19T11:33:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=clickonresource status=FAILURE method=TC_AddNewResource.clickonresource()[pri:2, instance:regression.TC_AddNewResource@10bdf5e5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - FAILED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewResource@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="3" started-at="2019-02-19T11:35:03Z" finished-at="2019-02-19T11:35:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addnewresource status=FAILURE method=TC_AddNewResource.addnewresource()[pri:3, instance:regression.TC_AddNewResource@10bdf5e5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - FAILED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="FAIL" signature="enterresourcedetails()[pri:4, instance:regression.TC_AddNewResource@10bdf5e5]" name="enterresourcedetails" duration-ms="33377" started-at="2019-02-19T11:35:03Z" finished-at="2019-02-19T11:35:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Not able to complete resource details]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Not able to complete resource details
at org.testng.Assert.fail(Assert.java:96)
at regression.TC_AddNewResource.enterresourcedetails(TC_AddNewResource.java:168)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterresourcedetails -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewResource@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="1" started-at="2019-02-19T11:35:36Z" finished-at="2019-02-19T11:35:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=enterresourcedetails status=FAILURE method=TC_AddNewResource.enterresourcedetails()[pri:4, instance:regression.TC_AddNewResource@10bdf5e5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - FAILED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="PASS" signature="logout()[pri:5, instance:regression.TC_AddNewResource@10bdf5e5]" name="logout" duration-ms="10848" started-at="2019-02-19T11:35:36Z" finished-at="2019-02-19T11:35:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="operationsOnTestCompletion(org.testng.ITestResult)[pri:0, instance:regression.TC_AddNewResource@10bdf5e5]" name="operationsOnTestCompletion" is-config="true" duration-ms="0" started-at="2019-02-19T11:35:47Z" finished-at="2019-02-19T11:35:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logout status=SUCCESS method=TC_AddNewResource.logout()[pri:5, instance:regression.TC_AddNewResource@10bdf5e5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ - PASSED.]]>
            </line>
          </reporter-output>
        </test-method> <!-- operationsOnTestCompletion -->
        <test-method status="PASS" signature="tearDownFunction()[pri:0, instance:regression.TC_AddNewResource@10bdf5e5]" name="tearDownFunction" is-config="true" duration-ms="738" started-at="2019-02-19T11:35:47Z" finished-at="2019-02-19T11:35:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownFunction -->
      </class> <!-- regression.TC_AddNewResource -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
