<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[C:\Users\satheeshnair\AppianJ&J\ExecutionReports\AutomationTestReport.html]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
    <line>
      <![CDATA[Exception in ExtentManager function]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="51836" started-at="2019-02-12T13:45:02Z" finished-at="2019-02-12T13:45:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="51836" started-at="2019-02-12T13:45:02Z" finished-at="2019-02-12T13:45:54Z">
      <class name="jj.test.TC_OrderOwner_Approval">
        <test-method status="PASS" signature="setup()[pri:0, instance:jj.test.TC_OrderOwner_Approval@204f30ec]" name="setup" is-config="true" duration-ms="6517" started-at="2019-02-12T13:44:55Z" finished-at="2019-02-12T13:45:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="loginasvendor()[pri:0, instance:jj.test.TC_OrderOwner_Approval@204f30ec]" name="loginasvendor" duration-ms="10115" started-at="2019-02-12T13:45:02Z" finished-at="2019-02-12T13:45:12Z">
          <reporter-output>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
            <line>
              <![CDATA[C:\Users\satheeshnair\AppianJ&J\ExecutionReports\AutomationTestReport.html]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginasvendor -->
        <test-method status="PASS" signature="clickontask()[pri:1, instance:jj.test.TC_OrderOwner_Approval@204f30ec]" name="clickontask" duration-ms="6993" started-at="2019-02-12T13:45:12Z" finished-at="2019-02-12T13:45:19Z">
          <reporter-output>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
          </reporter-output>
        </test-method> <!-- clickontask -->
        <test-method status="FAIL" signature="clickondemand()[pri:2, instance:jj.test.TC_OrderOwner_Approval@204f30ec]" name="clickondemand" duration-ms="3592" started-at="2019-02-12T13:45:19Z" finished-at="2019-02-12T13:45:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[no such demand]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: no such demand
at org.testng.Assert.fail(Assert.java:96)
at jj.test.TC_OrderOwner_Approval.clickondemand(TC_OrderOwner_Approval.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
          </reporter-output>
        </test-method> <!-- clickondemand -->
        <test-method status="PASS" signature="clickonpositionid()[pri:3, instance:jj.test.TC_OrderOwner_Approval@204f30ec]" name="clickonpositionid" duration-ms="19195" started-at="2019-02-12T13:45:23Z" finished-at="2019-02-12T13:45:42Z">
          <reporter-output>
            <line>
              <![CDATA[Exception in ExtentManager function]]>
            </line>
          </reporter-output>
        </test-method> <!-- clickonpositionid -->
        <test-method status="PASS" signature="logout()[pri:4, instance:jj.test.TC_OrderOwner_Approval@204f30ec]" name="logout" duration-ms="11908" started-at="2019-02-12T13:45:42Z" finished-at="2019-02-12T13:45:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:jj.test.TC_OrderOwner_Approval@204f30ec]" name="tearDown" is-config="true" duration-ms="350" started-at="2019-02-12T13:45:54Z" finished-at="2019-02-12T13:45:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- jj.test.TC_OrderOwner_Approval -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
